# Generated by Django 5.1.7 on 2025-03-30 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_dish_cooks_alter_dish_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_type', to='menu.dishtype'),
        ),
    ]
